### ISSUE TITLE
errors using bed2vcf.py on mac

### ISSUE THREAD

**Issue by bgold04** [YichaoOU/HemTools#8]
Hello,

Here is my command:

`python /Users/bgold/HemTools/bin/bed2vcf.py -f PanelBmosaik.bed --required_cols chr,pos,ID,ref,alt --info_col QUAL,DP,VD,AD,AF,RD,ALD,Func.refGene,REFGENE,GeneDetail.refGene,ExonicFunc.refGene,AAChange.refGene,Func.ensGene,Gene.ensGene,GeneDetail.ensGene,ExonicFunc.ensGene,AAChange.ensGene,Func.knownGene,Gene.knownGene,GeneDetail.knownGene,ExonicFunc.knownGene,AAChange.knownGene --info_types STRING,INTEGER,INTEGER,STRING,FLOAT,INTEGER,STRING,STRING,STRING,STRING,STRING,STRING,STRING,STRING,STRING,STRING,STRING,STRING,STRING,STRING,STRING,STRING -o PanelBmosaik.vcf`

Here is the reply:

```
Traceback (most recent call last):
  File "/Users/bgold/HemTools/bin/bed2vcf.py", line 137, in <module>
    main()
  File "/Users/bgold/HemTools/bin/bed2vcf.py", line 101, in main
    out = df[[chr,pos,ID,ref,alt]]
  File "/Users/bgold/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py", line 3030, in __getitem__
    indexer = self.loc._get_listlike_indexer(key, axis=1, raise_missing=True)[1]
  File "/Users/bgold/opt/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py", line 1266, in _get_listlike_indexer
    self._validate_read_indexer(keyarr, indexer, axis, raise_missing=raise_missing)
  File "/Users/bgold/opt/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py", line 1308, in _validate_read_indexer
    raise KeyError(f"None of [{key}] are in the [{axis_name}]")
KeyError: "None of [Index(['chr', 'pos', 'ID', 'ref', 'alt'], dtype='object')] are in the [columns]"
```

Here are the first ~30 lines of my input, space-delimited, no headers input file:

```
chr1 16258892 PanelB_LAB1_LIB4 AC A PASS 4592 29 4559,29 0.0063 17682791 10,19 exonic SPEN . frameshift substitution SPEN:NM_015001:exon11:c.6157_6158delinsA:p.N2053Tfs*11 exonic SPEN . frameshift substitution SPEN:ENST00000375759.8_1:exon11:c.6157_6158delinsA:p.N2053Tfs*11 exonic SPEN . frameshift substitution SPEN:uc010obp.1:exon10:c.6034_6035delinsA:p.N2012Tfs*11,SPEN:uc001axk.1:exon11:c.6157_6158delinsA:p.N2053Tfs*11
chr1 16258892 PanelB_LAB2_LIB2 AC A PASS 5911 31 5878,31 0.0052 24113467 13,18 exonic SPEN . frameshift substitution SPEN:NM_015001:exon11:c.6157_6158delinsA:p.N2053Tfs*11 exonic SPEN . frameshift substitution SPEN:ENST00000375759.8_1:exon11:c.6157_6158delinsA:p.N2053Tfs*11 exonic SPEN . frameshift substitution SPEN:uc010obp.1:exon10:c.6034_6035delinsA:p.N2012Tfs*11,SPEN:uc001axk.1:exon11:c.6157_6158delinsA:p.N2053Tfs*11
chr1 16258892 PanelB_LAB2_LIB3 AC A PASS 4369 23 4341,23 0.0053 17802561 11,12 exonic SPEN . frameshift substitution SPEN:NM_015001:exon11:c.6157_6158delinsA:p.N2053Tfs*11 exonic SPEN . frameshift substitution SPEN:ENST00000375759.8_1:exon11:c.6157_6158delinsA:p.N2053Tfs*11 exonic SPEN . frameshift substitution SPEN:uc010obp.1:exon10:c.6034_6035delinsA:p.N2012Tfs*11,SPEN:uc001axk.1:exon11:c.6157_6158delinsA:p.N2053Tfs*11
chr1 16258892 PanelB_LAB3_LIB1 AC A PASS 5297 28 5258,28 0.0053 18173441 5,23 exonic SPEN . frameshift substitution SPEN:NM_015001:exon11:c.6157_6158delinsA:p.N2053Tfs*11 exonic SPEN . frameshift substitution SPEN:ENST00000375759.8_1:exon11:c.6157_6158delinsA:p.N2053Tfs*11 exonic SPEN . frameshift substitution SPEN:uc010obp.1:exon10:c.6034_6035delinsA:p.N2012Tfs*11,SPEN:uc001axk.1:exon11:c.6157_6158delinsA:p.N2053Tfs*11
chr1 16258892 PanelB_LAB3_LIB2 AC A PASS 4932 33 4893,33 0.0067 16513242 10,23 exonic SPEN . frameshift substitution SPEN:NM_015001:exon11:c.6157_6158delinsA:p.N2053Tfs*11 exonic SPEN . frameshift substitution SPEN:ENST00000375759.8_1:exon11:c.6157_6158delinsA:p.N2053Tfs*11 exonic SPEN . frameshift substitution SPEN:uc010obp.1:exon10:c.6034_6035delinsA:p.N2012Tfs*11,SPEN:uc001axk.1:exon11:c.6157_6158delinsA:p.N2053Tfs*11
chr1 16258892 PanelB_LAB3_LIB3 AC A PASS 4444 29 4408,29 0.0065 14212987 13,16 exonic SPEN . frameshift substitution SPEN:NM_015001:exon11:c.6157_6158delinsA:p.N2053Tfs*11 exonic SPEN . frameshift substitution SPEN:ENST00000375759.8_1:exon11:c.6157_6158delinsA:p.N2053Tfs*11 exonic SPEN . frameshift substitution SPEN:uc010obp.1:exon10:c.6034_6035delinsA:p.N2012Tfs*11,SPEN:uc001axk.1:exon11:c.6157_6158delinsA:p.N2053Tfs*11
chr1 16258892 PanelB_LAB3_LIB4 AC A PASS 3848 27 3816,27 0.007 11962620 8,19 exonic SPEN . frameshift substitution SPEN:NM_015001:exon11:c.6157_6158delinsA:p.N2053Tfs*11 exonic SPEN . frameshift substitution SPEN:ENST00000375759.8_1:exon11:c.6157_6158delinsA:p.N2053Tfs*11 exonic SPEN . frameshift substitution SPEN:uc010obp.1:exon10:c.6034_6035delinsA:p.N2012Tfs*11,SPEN:uc001axk.1:exon11:c.6157_6158delinsA:p.N2053Tfs*11
chr1 16262463 PanelB_LAB3_LIB1 CA C PASS 2104 13 1961,13 0.0062 101951 11,2 exonic SPEN . frameshift substitution SPEN:NM_015001:exon11:c.9728_9729delinsC:p.T3244Pfs*40 exonic SPEN . frameshift substitution SPEN:ENST00000375759.8_1:exon11:c.9728_9729delinsC:p.T3244Pfs*40 exonic SPEN . frameshift substitution SPEN:uc010obp.1:exon10:c.9605_9606delinsC:p.T3203Pfs*40,SPEN:uc001axk.1:exon11:c.9728_9729delinsC:p.T3244Pfs*40
chr1 16262463 PanelB_LAB3_LIB2 CA C PASS 2041 14 1915,14 0.0069 61909 14,0 exonic SPEN . frameshift substitution SPEN:NM_015001:exon11:c.9728_9729delinsC:p.T3244Pfs*40 exonic SPEN . frameshift substitution SPEN:ENST00000375759.8_1:exon11:c.9728_9729delinsC:p.T3244Pfs*40 exonic SPEN . frameshift substitution SPEN:uc010obp.1:exon10:c.9605_9606delinsC:p.T3203Pfs*40,SPEN:uc001axk.1:exon11:c.9728_9729delinsC:p.T3244Pfs*40
chr1 16262678 PanelB_LAB1_LIB1 AC A PASS 4723 26 4695,26 0.0055 15883107 14,12 exonic SPEN . frameshift substitution SPEN:NM_015001:exon11:c.9943_9944delinsA:p.H3315Tfs*85 exonic SPEN . frameshift substitution SPEN:ENST00000375759.8_1:exon11:c.9943_9944delinsA:p.H3315Tfs*85 exonic SPEN . frameshift substitution SPEN:uc010obp.1:exon10:c.9820_9821delinsA:p.H3274Tfs*85,SPEN:uc001axk.1:exon11:c.9943_9944delinsA:p.H3315Tfs*85
chr1 16262678 PanelB_LAB2_LIB1 AC A PASS 4449 25 4422,25 0.0056 15322890 6,19 exonic SPEN . frameshift substitution SPEN:NM_015001:exon11:c.9943_9944delinsA:p.H3315Tfs*85 exonic SPEN . frameshift substitution SPEN:ENST00000375759.8_1:exon11:c.9943_9944delinsA:p.H3315Tfs*85 exonic SPEN . frameshift substitution SPEN:uc010obp.1:exon10:c.9820_9821delinsA:p.H3274Tfs*85,SPEN:uc001axk.1:exon11:c.9943_9944delinsA:p.H3315Tfs*85
chr1 16262678 PanelB_LAB2_LIB4 AC A PASS 3412 24 3388,24 0.007 12562132 10,14 exonic SPEN . frameshift substitution SPEN:NM_015001:exon11:c.9943_9944delinsA:p.H3315Tfs*85 exonic SPEN . frameshift substitution SPEN:ENST00000375759.8_1:exon11:c.9943_9944delinsA:p.H3315Tfs*85 exonic SPEN . frameshift substitution SPEN:uc010obp.1:exon10:c.9820_9821delinsA:p.H3274Tfs*85,SPEN:uc001axk.1:exon11:c.9943_9944delinsA:p.H3315Tfs*85
chr1 16262678 PanelB_LAB3_LIB1 AC A PASS 5719 35 5680,35 0.0061 14344246 17,18 exonic SPEN . frameshift substitution SPEN:NM_015001:exon11:c.9943_9944delinsA:p.H3315Tfs*85 exonic SPEN . frameshift substitution SPEN:ENST00000375759.8_1:exon11:c.9943_9944delinsA:p.H3315Tfs*85 exonic SPEN . frameshift substitution SPEN:uc010obp.1:exon10:c.9820_9821delinsA:p.H3274Tfs*85,SPEN:uc001axk.1:exon11:c.9943_9944delinsA:p.H3315Tfs*85
chr1 27105929 PanelB_LAB1_LIB1 TG T PASS 7340 38 7299,38 0.0052 33483951 22,16 exonic ARID1A . frameshift substitution ARID1A:NM_006015:exon20:c.5540_5541delinsT:p.G1847Vfs*36,ARID1A:NM_139135:exon20:c.4889_4890delinsT:p.G1630Vfs*36 exonic ARID1A . frameshift substitution ARID1A:ENST00000374152.7_1:exon19:c.4391_4392delinsT:p.G1464Vfs*36,ARID1A:ENST00000324856.13_1:exon20:c.5540_5541delinsT:p.G1847Vfs*36,ARID1A:ENST00000430799.7_1:exon20:c.4388_4389delinsT:p.G1463Vfs*36,ARID1A:ENST00000457599.6_1:exon20:c.4889_4890delinsT:p.G1630Vfs*36 exonic ARID1A . frameshift substitution ARID1A:uc009vsn.1:exon4:c.266_267delinsT:p.G89Vfs*36,ARID1A:uc009vsm.1:exon6:c.524_525delinsT:p.G175Vfs*36,ARID1A:uc001bmx.1:exon9:c.2078_2079delinsT:p.G693Vfs*36,ARID1A:uc001bmu.1:exon20:c.4889_4890delinsT:p.G1630Vfs*36,ARID1A:uc001bmv.1:exon20:c.5540_5541delinsT:p.G1847Vfs*36
chr1 27105929 PanelB_LAB2_LIB2 TG T PASS 8497 59 8435,59 0.0069 40044431 19,40 exonic ARID1A . frameshift substitution ARID1A:NM_006015:exon20:c.5540_5541delinsT:p.G1847Vfs*36,ARID1A:NM_139135:exon20:c.4889_4890delinsT:p.G1630Vfs*36 exonic ARID1A . frameshift substitution ARID1A:ENST00000374152.7_1:exon19:c.4391_4392delinsT:p.G1464Vfs*36,ARID1A:ENST00000324856.13_1:exon20:c.5540_5541delinsT:p.G1847Vfs*36,ARID1A:ENST00000430799.7_1:exon20:c.4388_4389delinsT:p.G1463Vfs*36,ARID1A:ENST00000457599.6_1:exon20:c.4889_4890delinsT:p.G1630Vfs*36 exonic ARID1A . frameshift substitution ARID1A:uc009vsn.1:exon4:c.266_267delinsT:p.G89Vfs*36,ARID1A:uc009vsm.1:exon6:c.524_525delinsT:p.G175Vfs*36,ARID1A:uc001bmx.1:exon9:c.2078_2079delinsT:p.G693Vfs*36,ARID1A:uc001bmu.1:exon20:c.4889_4890delinsT:p.G1630Vfs*36,ARID1A:uc001bmv.1:exon20:c.5540_5541delinsT:p.G1847Vfs*36
chr1 27105929 PanelB_LAB2_LIB4 TG T PASS 7067 52 7009,52 0.0074 34293580 36,16 exonic ARID1A . frameshift substitution ARID1A:NM_006015:exon20:c.5540_5541delinsT:p.G1847Vfs*36,ARID1A:NM_139135:exon20:c.4889_4890delinsT:p.G1630Vfs*36 exonic ARID1A . frameshift substitution ARID1A:ENST00000374152.7_1:exon19:c.4391_4392delinsT:p.G1464Vfs*36,ARID1A:ENST00000324856.13_1:exon20:c.5540_5541delinsT:p.G1847Vfs*36,ARID1A:ENST00000430799.7_1:exon20:c.4388_4389delinsT:p.G1463Vfs*36,ARID1A:ENST00000457599.6_1:exon20:c.4889_4890delinsT:p.G1630Vfs*36 exonic ARID1A . frameshift substitution ARID1A:uc009vsn.1:exon4:c.266_267delinsT:p.G89Vfs*36,ARID1A:uc009vsm.1:exon6:c.524_525delinsT:p.G175Vfs*36,ARID1A:uc001bmx.1:exon9:c.2078_2079delinsT:p.G693Vfs*36,ARID1A:uc001bmu.1:exon20:c.4889_4890delinsT:p.G1630Vfs*36,ARID1A:uc001bmv.1:exon20:c.5540_5541delinsT:p.G1847Vfs*36
chr1 27105929 PanelB_LAB3_LIB2 TG T PASS 7979 42 7926,42 0.0053 31174809 19,23 exonic ARID1A . frameshift substitution ARID1A:NM_006015:exon20:c.5540_5541delinsT:p.G1847Vfs*36,ARID1A:NM_139135:exon20:c.4889_4890delinsT:p.G1630Vfs*36 exonic ARID1A . frameshift substitution ARID1A:ENST00000374152.7_1:exon19:c.4391_4392delinsT:p.G1464Vfs*36,ARID1A:ENST00000324856.13_1:exon20:c.5540_5541delinsT:p.G1847Vfs*36,ARID1A:ENST00000430799.7_1:exon20:c.4388_4389delinsT:p.G1463Vfs*36,ARID1A:ENST00000457599.6_1:exon20:c.4889_4890delinsT:p.G1630Vfs*36 exonic ARID1A . frameshift substitution ARID1A:uc009vsn.1:exon4:c.266_267delinsT:p.G89Vfs*36,ARID1A:uc009vsm.1:exon6:c.524_525delinsT:p.G175Vfs*36,ARID1A:uc001bmx.1:exon9:c.2078_2079delinsT:p.G693Vfs*36,ARID1A:uc001bmu.1:exon20:c.4889_4890delinsT:p.G1630Vfs*36,ARID1A:uc001bmv.1:exon20:c.5540_5541delinsT:p.G1847Vfs*36
chr1 36935321 PanelB_LAB1_LIB4 TG T PASS 3912 21 3889,21 0.0054 12262663 9,12 exonic CSF3R . frameshift substitution CSF3R:NM_000760:exon11:c.1405_1406delinsA:p.S469Tfs*22,CSF3R:NM_156039:exon11:c.1405_1406delinsA:p.S469Tfs*22,CSF3R:NM_172313:exon11:c.1405_1406delinsA:p.S469Tfs*22 exonic CSF3R . frameshift substitution CSF3R:ENST00000331941.6_1:exon9:c.1405_1406delinsA:p.S469Tfs*22,CSF3R:ENST00000361632.8_1:exon9:c.1405_1406delinsA:p.S469Tfs*22,CSF3R:ENST00000373103.5_1:exon11:c.1405_1406delinsA:p.S469Tfs*22,CSF3R:ENST00000373104.5_1:exon11:c.1405_1406delinsA:p.S469Tfs*22,CSF3R:ENST00000373106.6_1:exon11:c.1405_1406delinsA:p.S469Tfs*22 exonic CSF3R . frameshift substitution CSF3R:uc001cav.2:exon11:c.1405_1406delinsA:p.S469Tfs*22,CSF3R:uc001caw.2:exon11:c.1405_1406delinsA:p.S469Tfs*22,CSF3R:uc001cax.2:exon11:c.1405_1406delinsA:p.S469Tfs*22
chr1 36935321 PanelB_LAB2_LIB2 TG T PASS 2933 18 2915,18 0.0061 9711944 6,12 exonic CSF3R . frameshift substitution CSF3R:NM_000760:exon11:c.1405_1406delinsA:p.S469Tfs*22,CSF3R:NM_156039:exon11:c.1405_1406delinsA:p.S469Tfs*22,CSF3R:NM_172313:exon11:c.1405_1406delinsA:p.S469Tfs*22 exonic CSF3R . frameshift substitution CSF3R:ENST00000331941.6_1:exon9:c.1405_1406delinsA:p.S469Tfs*22,CSF3R:ENST00000361632.8_1:exon9:c.1405_1406delinsA:p.S469Tfs*22,CSF3R:ENST00000373103.5_1:exon11:c.1405_1406delinsA:p.S469Tfs*22,CSF3R:ENST00000373104.5_1:exon11:c.1405_1406delinsA:p.S469Tfs*22,CSF3R:ENST00000373106.6_1:exon11:c.1405_1406delinsA:p.S469Tfs*22 exonic CSF3R . frameshift substitution CSF3R:uc001cav.2:exon11:c.1405_1406delinsA:p.S469Tfs*22,CSF3R:uc001caw.2:exon11:c.1405_1406delinsA:p.S469Tfs*22,CSF3R:uc001cax.2:exon11:c.1405_1406delinsA:p.S469Tfs*22
chr1 36935321 PanelB_LAB2_LIB4 TG T PASS 2342 15 2327,15 0.0064 7451582 2,13 exonic CSF3R . frameshift substitution CSF3R:NM_000760:exon11:c.1405_1406delinsA:p.S469Tfs*22,CSF3R:NM_156039:exon11:c.1405_1406delinsA:p.S469Tfs*22,CSF3R:NM_172313:exon11:c.1405_1406delinsA:p.S469Tfs*22 exonic CSF3R . frameshift substitution CSF3R:ENST00000331941.6_1:exon9:c.1405_1406delinsA:p.S469Tfs*22,CSF3R:ENST00000361632.8_1:exon9:c.1405_1406delinsA:p.S469Tfs*22,CSF3R:ENST00000373103.5_1:exon11:c.1405_1406delinsA:p.S469Tfs*22,CSF3R:ENST00000373104.5_1:exon11:c.1405_1406delinsA:p.S469Tfs*22,CSF3R:ENST00000373106.6_1:exon11:c.1405_1406delinsA:p.S469Tfs*22 exonic CSF3R . frameshift substitution CSF3R:uc001cav.2:exon11:c.1405_1406delinsA:p.S469Tfs*22,CSF3R:uc001caw.2:exon11:c.1405_1406delinsA:p.S469Tfs*22,CSF3R:uc001cax.2:exon11:c.1405_1406delinsA:p.S469Tfs*22
chr1 36935321 PanelB_LAB3_LIB3 TG T PASS 2900 15 2884,15 0.0052 6842200 4,11 exonic CSF3R . frameshift substitution CSF3R:NM_000760:exon11:c.1405_1406delinsA:p.S469Tfs*22,CSF3R:NM_156039:exon11:c.1405_1406delinsA:p.S469Tfs*22,CSF3R:NM_172313:exon11:c.1405_1406delinsA:p.S469Tfs*22 exonic CSF3R . frameshift substitution CSF3R:ENST00000331941.6_1:exon9:c.1405_1406delinsA:p.S469Tfs*22,CSF3R:ENST00000361632.8_1:exon9:c.1405_1406delinsA:p.S469Tfs*22,CSF3R:ENST00000373103.5_1:exon11:c.1405_1406delinsA:p.S469Tfs*22,CSF3R:ENST00000373104.5_1:exon11:c.1405_1406delinsA:p.S469Tfs*22,CSF3R:ENST00000373106.6_1:exon11:c.1405_1406delinsA:p.S469Tfs*22 exonic CSF3R . frameshift substitution CSF3R:uc001cav.2:exon11:c.1405_1406delinsA:p.S469Tfs*22,CSF3R:uc001caw.2:exon11:c.1405_1406delinsA:p.S469Tfs*22,CSF3R:uc001cax.2:exon11:c.1405_1406delinsA:p.S469Tfs*22
chr1 65325831 PanelB_LAB1_LIB2 CG C PASS 3359 20 3338,20 0.006 12722066 13,7 exonic JAK1 . stopgain JAK1:NM_001321852:exon9:c.1290_1291delinsG:p.L431*,JAK1:NM_001321856:exon9:c.1290_1291delinsG:p.L431*,JAK1:NM_001321857:exon9:c.1290_1291delinsG:p.L431*,JAK1:NM_002227:exon9:c.1290_1291delinsG:p.L431*,JAK1:NM_001320923:exon10:c.1290_1291delinsG:p.L431*,JAK1:NM_001321854:exon10:c.1290_1291delinsG:p.L431*,JAK1:NM_001321855:exon10:c.1290_1291delinsG:p.L431*,JAK1:NM_001321853:exon11:c.1290_1291delinsG:p.L431* exonic JAK1 . stopgain JAK1:ENST00000342505.5_1:exon9:c.1290_1291delinsG:p.L431*,JAK1:ENST00000672179.1_1:exon9:c.1290_1291delinsG:p.L431*,JAK1:ENST00000673046.1_1:exon9:c.1290_1291delinsG:p.L431*,JAK1:ENST00000673254.1_1:exon9:c.1158_1159delinsG:p.L387*,JAK1:ENST00000671929.1_1:exon10:c.1290_1291delinsG:p.L431*,JAK1:ENST00000671954.1_1:exon10:c.1290_1291delinsG:p.L431*,JAK1:ENST00000672247.1_1:exon10:c.1290_1291delinsG:p.L431*,JAK1:ENST00000672434.1_1:exon11:c.1290_1291delinsG:p.L431*,JAK1:ENST00000673502.1_1:exon11:c.1290_1291delinsG:p.L431* exonic JAK1 . stopgain JAK1:uc001dbu.1:exon9:c.1290_1291delinsG:p.L431*,JAK1:uc009wam.1:exon10:c.1290_1291delinsG:p.L431*   
chr1 65325831 PanelB_LAB2_LIB2 CG C PASS 3274 18 3253,18 0.0055 12372016 8,10 exonic JAK1 . stopgain JAK1:NM_001321852:exon9:c.1290_1291delinsG:p.L431*,JAK1:NM_001321856:exon9:c.1290_1291delinsG:p.L431*,JAK1:NM_001321857:exon9:c.1290_1291delinsG:p.L431*,JAK1:NM_002227:exon9:c.1290_1291delinsG:p.L431*,JAK1:NM_001320923:exon10:c.1290_1291delinsG:p.L431*,JAK1:NM_001321854:exon10:c.1290_1291delinsG:p.L431*,JAK1:NM_001321855:exon10:c.1290_1291delinsG:p.L431*,JAK1:NM_001321853:exon11:c.1290_1291delinsG:p.L431* exonic JAK1 . stopgain JAK1:ENST00000342505.5_1:exon9:c.1290_1291delinsG:p.L431*,JAK1:ENST00000672179.1_1:exon9:c.1290_1291delinsG:p.L431*,JAK1:ENST00000673046.1_1:exon9:c.1290_1291delinsG:p.L431*,JAK1:ENST00000673254.1_1:exon9:c.1158_1159delinsG:p.L387*,JAK1:ENST00000671929.1_1:exon10:c.1290_1291delinsG:p.L431*,JAK1:ENST00000671954.1_1:exon10:c.1290_1291delinsG:p.L431*,JAK1:ENST00000672247.1_1:exon10:c.1290_1291delinsG:p.L431*,JAK1:ENST00000672434.1_1:exon11:c.1290_1291delinsG:p.L431*,JAK1:ENST00000673502.1_1:exon11:c.1290_1291delinsG:p.L431* exonic JAK1 . stopgain JAK1:uc001dbu.1:exon9:c.1290_1291delinsG:p.L431*,JAK1:uc009wam.1:exon10:c.1290_1291delinsG:p.L431*   
chr1 65325831 PanelB_LAB2_LIB4 CG C PASS 2496 14 2478,14 0.0056 10301448 2,12 exonic JAK1 . stopgain JAK1:NM_001321852:exon9:c.1290_1291delinsG:p.L431*,JAK1:NM_001321856:exon9:c.1290_1291delinsG:p.L431*,JAK1:NM_001321857:exon9:c.1290_1291delinsG:p.L431*,JAK1:NM_002227:exon9:c.1290_1291delinsG:p.L431*,JAK1:NM_001320923:exon10:c.1290_1291delinsG:p.L431*,JAK1:NM_001321854:exon10:c.1290_1291delinsG:p.L431*,JAK1:NM_001321855:exon10:c.1290_1291delinsG:p.L431*,JAK1:NM_001321853:exon11:c.1290_1291delinsG:p.L431* exonic JAK1 . stopgain JAK1:ENST00000342505.5_1:exon9:c.1290_1291delinsG:p.L431*,JAK1:ENST00000672179.1_1:exon9:c.1290_1291delinsG:p.L431*,JAK1:ENST00000673046.1_1:exon9:c.1290_1291delinsG:p.L431*,JAK1:ENST00000673254.1_1:exon9:c.1158_1159delinsG:p.L387*,JAK1:ENST00000671929.1_1:exon10:c.1290_1291delinsG:p.L431*,JAK1:ENST00000671954.1_1:exon10:c.1290_1291delinsG:p.L431*,JAK1:ENST00000672247.1_1:exon10:c.1290_1291delinsG:p.L431*,JAK1:ENST00000672434.1_1:exon11:c.1290_1291delinsG:p.L431*,JAK1:ENST00000673502.1_1:exon11:c.1290_1291delinsG:p.L431* exonic JAK1 . stopgain JAK1:uc001dbu.1:exon9:c.1290_1291delinsG:p.L431*,JAK1:uc009wam.1:exon10:c.1290_1291delinsG:p.L431*   
chr1 65325831 PanelB_LAB3_LIB2 CG C PASS 3741 19 3714,19 0.0051 11622552 9,10 exonic JAK1 . stopgain JAK1:NM_001321852:exon9:c.1290_1291delinsG:p.L431*,JAK1:NM_001321856:exon9:c.1290_1291delinsG:p.L431*,JAK1:NM_001321857:exon9:c.1290_1291delinsG:p.L431*,JAK1:NM_002227:exon9:c.1290_1291delinsG:p.L431*,JAK1:NM_001320923:exon10:c.1290_1291delinsG:p.L431*,JAK1:NM_001321854:exon10:c.1290_1291delinsG:p.L431*,JAK1:NM_001321855:exon10:c.1290_1291delinsG:p.L431*,JAK1:NM_001321853:exon11:c.1290_1291delinsG:p.L431* exonic JAK1 . stopgain JAK1:ENST00000342505.5_1:exon9:c.1290_1291delinsG:p.L431*,JAK1:ENST00000672179.1_1:exon9:c.1290_1291delinsG:p.L431*,JAK1:ENST00000673046.1_1:exon9:c.1290_1291delinsG:p.L431*,JAK1:ENST00000673254.1_1:exon9:c.1158_1159delinsG:p.L387*,JAK1:ENST00000671929.1_1:exon10:c.1290_1291delinsG:p.L431*,JAK1:ENST00000671954.1_1:exon10:c.1290_1291delinsG:p.L431*,JAK1:ENST00000672247.1_1:exon10:c.1290_1291delinsG:p.L431*,JAK1:ENST00000672434.1_1:exon11:c.1290_1291delinsG:p.L431*,JAK1:ENST00000673502.1_1:exon11:c.1290_1291delinsG:p.L431* exonic JAK1 . stopgain JAK1:uc001dbu.1:exon9:c.1290_1291delinsG:p.L431*,JAK1:uc009wam.1:exon10:c.1290_1291delinsG:p.L431*   
chr1 65325831 PanelB_LAB3_LIB3 CG C PASS 3232 20 3205,20 0.0062 9822223 4,16 exonic JAK1 . stopgain JAK1:NM_001321852:exon9:c.1290_1291delinsG:p.L431*,JAK1:NM_001321856:exon9:c.1290_1291delinsG:p.L431*,JAK1:NM_001321857:exon9:c.1290_1291delinsG:p.L431*,JAK1:NM_002227:exon9:c.1290_1291delinsG:p.L431*,JAK1:NM_001320923:exon10:c.1290_1291delinsG:p.L431*,JAK1:NM_001321854:exon10:c.1290_1291delinsG:p.L431*,JAK1:NM_001321855:exon10:c.1290_1291delinsG:p.L431*,JAK1:NM_001321853:exon11:c.1290_1291delinsG:p.L431* exonic JAK1 . stopgain JAK1:ENST00000342505.5_1:exon9:c.1290_1291delinsG:p.L431*,JAK1:ENST00000672179.1_1:exon9:c.1290_1291delinsG:p.L431*,JAK1:ENST00000673046.1_1:exon9:c.1290_1291delinsG:p.L431*,JAK1:ENST00000673254.1_1:exon9:c.1158_1159delinsG:p.L387*,JAK1:ENST00000671929.1_1:exon10:c.1290_1291delinsG:p.L431*,JAK1:ENST00000671954.1_1:exon10:c.1290_1291delinsG:p.L431*,JAK1:ENST00000672247.1_1:exon10:c.1290_1291delinsG:p.L431*,JAK1:ENST00000672434.1_1:exon11:c.1290_1291delinsG:p.L431*,JAK1:ENST00000673502.1_1:exon11:c.1290_1291delinsG:p.L431* exonic JAK1 . stopgain JAK1:uc001dbu.1:exon9:c.1290_1291delinsG:p.L431*,JAK1:uc009wam.1:exon10:c.1290_1291delinsG:p.L431*   
chr1 65325831 PanelB_LAB3_LIB4 CG C PASS 2934 15 2911,15 0.0051 9711940 6,9 exonic JAK1 . stopgain JAK1:NM_001321852:exon9:c.1290_1291delinsG:p.L431*,JAK1:NM_001321856:exon9:c.1290_1291delinsG:p.L431*,JAK1:NM_001321857:exon9:c.1290_1291delinsG:p.L431*,JAK1:NM_002227:exon9:c.1290_1291delinsG:p.L431*,JAK1:NM_001320923:exon10:c.1290_1291delinsG:p.L431*,JAK1:NM_001321854:exon10:c.1290_1291delinsG:p.L431*,JAK1:NM_001321855:exon10:c.1290_1291delinsG:p.L431*,JAK1:NM_001321853:exon11:c.1290_1291delinsG:p.L431* exonic JAK1 . stopgain JAK1:ENST00000342505.5_1:exon9:c.1290_1291delinsG:p.L431*,JAK1:ENST00000672179.1_1:exon9:c.1290_1291delinsG:p.L431*,JAK1:ENST00000673046.1_1:exon9:c.1290_1291delinsG:p.L431*,JAK1:ENST00000673254.1_1:exon9:c.1158_1159delinsG:p.L387*,JAK1:ENST00000671929.1_1:exon10:c.1290_1291delinsG:p.L431*,JAK1:ENST00000671954.1_1:exon10:c.1290_1291delinsG:p.L431*,JAK1:ENST00000672247.1_1:exon10:c.1290_1291delinsG:p.L431*,JAK1:ENST00000672434.1_1:exon11:c.1290_1291delinsG:p.L431*,JAK1:ENST00000673502.1_1:exon11:c.1290_1291delinsG:p.L431* exonic JAK1 . stopgain JAK1:uc001dbu.1:exon9:c.1290_1291delinsG:p.L431*,JAK1:uc009wam.1:exon10:c.1290_1291delinsG:p.L431*   
chr1 85733511 PanelB_LAB1_LIB1 GA G PASS 3656 25 3631,25 0.0068 12452386 5,20 exonic BCL10 . frameshift substitution BCL10:NM_001320715:exon3:c.467_468delinsC:p.T157Lfs*5,BCL10:NM_003921:exon3:c.500_501delinsC:p.T168Lfs*5 exonic BCL10 . frameshift substitution BCL10:ENST00000620248.2_1:exon3:c.467_468delinsC:p.T157Lfs*5,BCL10:ENST00000648566.1_1:exon3:c.500_501delinsC:p.T168Lfs*5 exonic BCL10 . frameshift substitution BCL10:uc021opd.1:exon3:c.500_501delinsC:p.T168Lfs*5
chr1 85733511 PanelB_LAB1_LIB2 GA G PASS 4535 24 4507,24 0.0053 15092998 8,16 exonic BCL10 . frameshift substitution BCL10:NM_001320715:exon3:c.467_468delinsC:p.T157Lfs*5,BCL10:NM_003921:exon3:c.500_501delinsC:p.T168Lfs*5 exonic BCL10 . frameshift substitution BCL10:ENST00000620248.2_1:exon3:c.467_468delinsC:p.T157Lfs*5,BCL10:ENST00000648566.1_1:exon3:c.500_501delinsC:p.T168Lfs*5 exonic BCL10 . frameshift substitution BCL10:uc021opd.1:exon3:c.500_501delinsC:p.T168Lfs*5
chr1 85733511 PanelB_LAB2_LIB1 GA G PASS 4619 24 4593,24 0.0052 14663127 16,8 exonic BCL10 . frameshift substitution BCL10:NM_001320715:exon3:c.467_468delinsC:p.T157Lfs*5,BCL10:NM_003921:exon3:c.500_501delinsC:p.T168Lfs*5 exonic BCL10 . frameshift substitution BCL10:ENST00000620248.2_1:exon3:c.467_468delinsC:p.T157Lfs*5,BCL10:ENST00000648566.1_1:exon3:c.500_501delinsC:p.T168Lfs*5 exonic BCL10 . frameshift substitution BCL10:uc021opd.1:exon3:c.500_501delinsC:p.T168Lfs*5
chr1 85733511 PanelB_LAB3_LIB3 GA G PASS 3883 24 3855,24 0.0062 11862669 8,16 exonic BCL10 . frameshift substitution BCL10:NM_001320715:exon3:c.467_468delinsC:p.T157Lfs*5,BCL10:NM_003921:exon3:c.500_501delinsC:p.T168Lfs*5 exonic BCL10 . frameshift substitution BCL10:ENST00000620248.2_1:exon3:c.467_468delinsC:p.T157Lfs*5,BCL10:ENST00000648566.1_1:exon3:c.500_501delinsC:p.T168Lfs*5 exonic BCL10 . frameshift substitution BCL10:uc021opd.1:exon3:c.500_501delinsC:p.T168Lfs*5
```
OK, so where am I messing up?

Suggestions welcomed.

**Comment by YichaoOU** [comment]
Sorry that my `bed2vcf.py` is not a generic script. For you case, it is much easier if you write your own program.
